version: '3.8'

services:

  db:
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRES_DATABASE: quiz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hatikmi
    ports:
      - "5434:5432"
  spring-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/quiz
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: hatikmi